# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake

# The command to remove a file.
RM = /home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/haseenasainul/br-builds/buildroot-17Nov/output/build/wpeframework-14c858dda094aa76abfe2204ba4e85dc73150b4d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/haseenasainul/br-builds/buildroot-17Nov/output/build/wpeframework-14c858dda094aa76abfe2204ba4e85dc73150b4d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@echo "Installing the project stripped..."
	/home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@echo "Installing the project stripped..."
	/home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@echo "Install the project..."
	/home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo "Install the project..."
	/home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@echo "Installing only the local directory..."
	/home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@echo "Installing only the local directory..."
	/home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@echo "Available install components are: \"Unspecified\" \"devel\" \"libs\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@echo "No interactive CMake dialog available..."
	/home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/home/haseenasainul/br-builds/buildroot-17Nov/output/host/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haseenasainul/br-builds/buildroot-17Nov/output/build/wpeframework-14c858dda094aa76abfe2204ba4e85dc73150b4d/CMakeFiles /home/haseenasainul/br-builds/buildroot-17Nov/output/build/wpeframework-14c858dda094aa76abfe2204ba4e85dc73150b4d/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haseenasainul/br-builds/buildroot-17Nov/output/build/wpeframework-14c858dda094aa76abfe2204ba4e85dc73150b4d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WPEFrameworkCore

# Build rule for target.
WPEFrameworkCore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEFrameworkCore
.PHONY : WPEFrameworkCore

# fast build rule for target.
WPEFrameworkCore/fast:
	$(MAKE) -f Source/core/CMakeFiles/WPEFrameworkCore.dir/build.make Source/core/CMakeFiles/WPEFrameworkCore.dir/build
.PHONY : WPEFrameworkCore/fast

#=============================================================================
# Target rules for targets named WPEFrameworkCryptalgo

# Build rule for target.
WPEFrameworkCryptalgo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEFrameworkCryptalgo
.PHONY : WPEFrameworkCryptalgo

# fast build rule for target.
WPEFrameworkCryptalgo/fast:
	$(MAKE) -f Source/cryptalgo/CMakeFiles/WPEFrameworkCryptalgo.dir/build.make Source/cryptalgo/CMakeFiles/WPEFrameworkCryptalgo.dir/build
.PHONY : WPEFrameworkCryptalgo/fast

#=============================================================================
# Target rules for targets named WPEFrameworkWebSocket

# Build rule for target.
WPEFrameworkWebSocket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEFrameworkWebSocket
.PHONY : WPEFrameworkWebSocket

# fast build rule for target.
WPEFrameworkWebSocket/fast:
	$(MAKE) -f Source/websocket/CMakeFiles/WPEFrameworkWebSocket.dir/build.make Source/websocket/CMakeFiles/WPEFrameworkWebSocket.dir/build
.PHONY : WPEFrameworkWebSocket/fast

#=============================================================================
# Target rules for targets named WPEFrameworkTracing

# Build rule for target.
WPEFrameworkTracing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEFrameworkTracing
.PHONY : WPEFrameworkTracing

# fast build rule for target.
WPEFrameworkTracing/fast:
	$(MAKE) -f Source/tracing/CMakeFiles/WPEFrameworkTracing.dir/build.make Source/tracing/CMakeFiles/WPEFrameworkTracing.dir/build
.PHONY : WPEFrameworkTracing/fast

#=============================================================================
# Target rules for targets named WPEFrameworkCOM

# Build rule for target.
WPEFrameworkCOM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEFrameworkCOM
.PHONY : WPEFrameworkCOM

# fast build rule for target.
WPEFrameworkCOM/fast:
	$(MAKE) -f Source/com/CMakeFiles/WPEFrameworkCOM.dir/build.make Source/com/CMakeFiles/WPEFrameworkCOM.dir/build
.PHONY : WPEFrameworkCOM/fast

#=============================================================================
# Target rules for targets named WPEFrameworkProxyStubs

# Build rule for target.
WPEFrameworkProxyStubs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEFrameworkProxyStubs
.PHONY : WPEFrameworkProxyStubs

# fast build rule for target.
WPEFrameworkProxyStubs/fast:
	$(MAKE) -f Source/proxystubs/CMakeFiles/WPEFrameworkProxyStubs.dir/build.make Source/proxystubs/CMakeFiles/WPEFrameworkProxyStubs.dir/build
.PHONY : WPEFrameworkProxyStubs/fast

#=============================================================================
# Target rules for targets named WPEFrameworkPlugins

# Build rule for target.
WPEFrameworkPlugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEFrameworkPlugins
.PHONY : WPEFrameworkPlugins

# fast build rule for target.
WPEFrameworkPlugins/fast:
	$(MAKE) -f Source/plugins/CMakeFiles/WPEFrameworkPlugins.dir/build.make Source/plugins/CMakeFiles/WPEFrameworkPlugins.dir/build
.PHONY : WPEFrameworkPlugins/fast

#=============================================================================
# Target rules for targets named WPEProcess

# Build rule for target.
WPEProcess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEProcess
.PHONY : WPEProcess

# fast build rule for target.
WPEProcess/fast:
	$(MAKE) -f Source/WPEProcess/CMakeFiles/WPEProcess.dir/build.make Source/WPEProcess/CMakeFiles/WPEProcess.dir/build
.PHONY : WPEProcess/fast

#=============================================================================
# Target rules for targets named WPEFramework

# Build rule for target.
WPEFramework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WPEFramework
.PHONY : WPEFramework

# fast build rule for target.
WPEFramework/fast:
	$(MAKE) -f Source/WPEFramework/CMakeFiles/WPEFramework.dir/build.make Source/WPEFramework/CMakeFiles/WPEFramework.dir/build
.PHONY : WPEFramework/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... WPEFrameworkCore"
	@echo "... WPEFrameworkCryptalgo"
	@echo "... WPEFrameworkWebSocket"
	@echo "... WPEFrameworkTracing"
	@echo "... WPEFrameworkCOM"
	@echo "... WPEFrameworkProxyStubs"
	@echo "... WPEFrameworkPlugins"
	@echo "... WPEProcess"
	@echo "... WPEFramework"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

