/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2024 Metrological
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef THUNDER_DISTRIBUTED_TRACING

#include <string>
#include <unordered_map>
#include <mutex>
#include <atomic>
#include <chrono>
#include <cstdint>

namespace WPEFramework {

namespace PluginHost {

// ─────────────────────────────────────────────────────────────────────────────
// SpanMetadata
//
// Per-active-span bookkeeping.  Stored in the _activeSpans map keyed by an
// opaque uint64_t spanId generated by NextSpanId().
// ─────────────────────────────────────────────────────────────────────────────
struct SpanMetadata {
    std::string callsign;
    std::string operation;
    std::chrono::steady_clock::time_point startTime{std::chrono::steady_clock::now()};

    double ElapsedMs() const {
        return std::chrono::duration<double, std::milli>(
            std::chrono::steady_clock::now() - startTime).count();
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// DistributedTracing
//
// Singleton that manages the Thunder-side distributed tracing lifecycle.
// Delegates ALL OTEL operations to librdk_otlp_instrumentation via symbols
// resolved lazily at runtime with dlsym(RTLD_DEFAULT).  The WPEFramework
// binary therefore has zero hard dependency on librdk_otlp — if the library
// is absent the singleton is a complete no-op.
//
// Trace context propagation model:
//   JSON-RPC:  Thunder calls rdk_otlp_get_current_traceparent() to read the
//              W3C traceparent from TLS (set by the caller) and creates a
//              child span from it.  No pre-agreed naming convention needed —
//              propagation is automatic for any caller that holds an active
//              span.
//   COM-RPC:   IUnknown.cpp stamps the TLS traceparent into the binary
//              message header.  Administrator.cpp reads it on the stub side
//              and calls ICOMRPCStubTraceCallbacks::onBegin/onEnd which are
//              wired to OnCOMRPCStubBegin/End here.
// ─────────────────────────────────────────────────────────────────────────────
class DistributedTracing {
public:
    DistributedTracing(const DistributedTracing&) = delete;
    DistributedTracing& operator=(const DistributedTracing&) = delete;

    static DistributedTracing& Instance();

    // Lifecycle ───────────────────────────────────────────────────────────────
    void Initialize();   // call once after rdk_otlp_init() in PluginHost.cpp
    void Shutdown();     // call on WPEFramework shutdown
    bool IsEnabled() const { return _enabled.load(std::memory_order_acquire); }

    // ─────────────────────────────────────────────────────────────────────────
    // JSON-RPC path
    //
    // Called from PluginServer.h Invoke() wrapper.
    // traceparent is the W3C traceparent string extracted from the incoming
    // JSON-RPC params (_tp field injected by JSONRPCLink on the caller side).
    // Must NOT be read from TLS here — JSON-RPC dispatches on Thunder's thread
    // pool, not the caller's thread.
    // Returns a spanId handle that must be passed to OnInvokeEnd().
    // Returns 0 if traceparent is null/empty (no active trace from caller).
    // ─────────────────────────────────────────────────────────────────────────
    uint64_t OnInvokeBegin(const std::string& callsign, const std::string& method,
                           uint32_t channelId, const char* traceparent);
    void     OnInvokeEnd(uint64_t spanId, uint32_t result);

    // ─────────────────────────────────────────────────────────────────────────
    // COM-RPC stub path
    //
    // Called by Administrator.cpp via the registered ICOMRPCStubTraceCallbacks.
    // traceparent arrives inside the binary COM-RPC message header.
    // ─────────────────────────────────────────────────────────────────────────
    static void OnCOMRPCStubBegin(uint32_t interfaceId, uint8_t methodId,
                                  const char* traceparent);
    static void OnCOMRPCStubEnd(uint32_t interfaceId, uint8_t methodId);

private:
    DistributedTracing();
    ~DistributedTracing();

    uint64_t NextSpanId();

    std::atomic<bool>     _enabled{false};
    std::atomic<uint64_t> _spanCounter{0};

    mutable std::mutex                          _spanLock;
    std::unordered_map<uint64_t, SpanMetadata>  _activeSpans;

    // Thread-local stub span IDs so onEnd can match onBegin on the same thread.
    // Each COM-RPC worker thread independently tracks its current stub span.
};

} // namespace PluginHost

} // namespace WPEFramework

#endif // THUNDER_DISTRIBUTED_TRACING
