/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2020 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "Profile.h"

namespace WPEFramework {

ENUM_CONVERSION_BEGIN(Bluetooth::Profile::Service::Characteristic::Descriptor::type)

    { Bluetooth::Profile::Service::Characteristic::Descriptor::CharacteristicAggregateFormat,      _TXT("CharacteristicAggregateFormat") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::CharacteristicExtendedPropertie,    _TXT("CharacteristicExtendedPropertie") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::CharacteristicPresentationFormat,   _TXT("CharacteristicPresentationFormat") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::CharacteristicUserDescription,      _TXT("CharacteristicUserDescription") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::ClientCharacteristicConfiguration,  _TXT("ClientCharacteristicConfiguration") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::EnvironmentalSensingConfiguration,  _TXT("EnvironmentalSensingConfiguration") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::EnvironmentalSensingMeasurement,    _TXT("EnvironmentalSensingMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::EnvironmentalSensingTriggerSetting, _TXT("EnvironmentalSensingTriggerSetting") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::ExternalReportReference,            _TXT("ExternalReportReference") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::NumberOfDigital,                    _TXT("NumberOfDigital") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::ReportReference,                    _TXT("ReportReference") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::ServerCharacteristicConfiguration,  _TXT("ServerCharacteristicConfiguration") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::TimeTriggerSetting,                 _TXT("TimeTriggerSetting") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::ValidRange,                         _TXT("ValidRange") },
    { Bluetooth::Profile::Service::Characteristic::Descriptor::ValueTriggerSetting,                _TXT("ValueTriggerSetting") },

ENUM_CONVERSION_END(Bluetooth::Profile::Service::Characteristic::Descriptor::type)

ENUM_CONVERSION_BEGIN(Bluetooth::Profile::Service::Characteristic::type)

    { Bluetooth::Profile::Service::Characteristic::AerobicHeartRateLowerLimit,                _TXT("AerobicHeartRateLowerLimit") },
    { Bluetooth::Profile::Service::Characteristic::AerobicHeartRateUpperLimit,                _TXT("AerobicHeartRateUpperLimit") },
    { Bluetooth::Profile::Service::Characteristic::AerobicThreshold,                          _TXT("AerobicThreshold") },
    { Bluetooth::Profile::Service::Characteristic::Age,                                       _TXT("Age") },
    { Bluetooth::Profile::Service::Characteristic::Aggregate,                                 _TXT("Aggregate") },
    { Bluetooth::Profile::Service::Characteristic::AlertCategoryID,                           _TXT("AlertCategoryID") },
    { Bluetooth::Profile::Service::Characteristic::AlertCategoryIDBitMask,                    _TXT("AlertCategoryIDBitMask") },
    { Bluetooth::Profile::Service::Characteristic::AlertLevel,                                _TXT("AlertLevel") },
    { Bluetooth::Profile::Service::Characteristic::AlertNotificationControlPoint,             _TXT("AlertNotificationControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::AlertStatus,                               _TXT("AlertStatus") },
    { Bluetooth::Profile::Service::Characteristic::Altitude,                                  _TXT("Altitude") },
    { Bluetooth::Profile::Service::Characteristic::AnaerobicHeartRateLowerLimit,              _TXT("AnaerobicHeartRateLowerLimit") },
    { Bluetooth::Profile::Service::Characteristic::AnaerobicHeartRateUpperLimit,              _TXT("AnaerobicHeartRateUpperLimit") },
    { Bluetooth::Profile::Service::Characteristic::AnaerobicThreshold,                        _TXT("AnaerobicThreshold") },
    { Bluetooth::Profile::Service::Characteristic::Analog,                                    _TXT("Analog") },
    { Bluetooth::Profile::Service::Characteristic::AnalogOutput,                              _TXT("AnalogOutput") },
    { Bluetooth::Profile::Service::Characteristic::ApparentWindDirection,                     _TXT("ApparentWindDirection") },
    { Bluetooth::Profile::Service::Characteristic::ApparentWindSpeed,                         _TXT("ApparentWindSpeed") },
    { Bluetooth::Profile::Service::Characteristic::Appearance,                                _TXT("Appearance") },
    { Bluetooth::Profile::Service::Characteristic::BarometricPressureTrend,                   _TXT("BarometricPressureTrend") },
    { Bluetooth::Profile::Service::Characteristic::BatteryLevel,                              _TXT("BatteryLevel") },
    { Bluetooth::Profile::Service::Characteristic::BatteryLevelState,                         _TXT("BatteryLevelState") },
    { Bluetooth::Profile::Service::Characteristic::BatteryPowerState,                         _TXT("BatteryPowerState") },
    { Bluetooth::Profile::Service::Characteristic::BloodPressureFeature,                      _TXT("BloodPressureFeature") },
    { Bluetooth::Profile::Service::Characteristic::BloodPressureMeasurement,                  _TXT("BloodPressureMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::BodyCompositionFeature,                    _TXT("BodyCompositionFeature") },
    { Bluetooth::Profile::Service::Characteristic::BodyCompositionMeasurement,                _TXT("BodyCompositionMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::BodySensorLocation,                        _TXT("BodySensorLocation") },
    { Bluetooth::Profile::Service::Characteristic::BondManagementControlPoint,                _TXT("BondManagementControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::BondManagementFeatures,                    _TXT("BondManagementFeatures") },
    { Bluetooth::Profile::Service::Characteristic::BootKeyboardInputReport,                   _TXT("BootKeyboardInputReport") },
    { Bluetooth::Profile::Service::Characteristic::BootKeyboardOutputReport,                  _TXT("BootKeyboardOutputReport") },
    { Bluetooth::Profile::Service::Characteristic::BootMouseInputReport,                      _TXT("BootMouseInputReport") },
    { Bluetooth::Profile::Service::Characteristic::BSSControlPoint,                           _TXT("BSSControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::BSSResponse,                               _TXT("BSSResponse") },
    { Bluetooth::Profile::Service::Characteristic::CGMFeature,                                _TXT("CGMFeature") },
    { Bluetooth::Profile::Service::Characteristic::CGMMeasurement,                            _TXT("CGMMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::CGMSessionRunTime,                         _TXT("CGMSessionRunTime") },
    { Bluetooth::Profile::Service::Characteristic::CGMSessionStartTime,                       _TXT("CGMSessionStartTime") },
    { Bluetooth::Profile::Service::Characteristic::CGMSpecificOpsControlPoint,                _TXT("CGMSpecificOpsControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::CGMStatus,                                 _TXT("CGMStatus") },
    { Bluetooth::Profile::Service::Characteristic::CrossTrainerData,                          _TXT("CrossTrainerData") },
    { Bluetooth::Profile::Service::Characteristic::CSCFeature,                                _TXT("CSCFeature") },
    { Bluetooth::Profile::Service::Characteristic::CSCMeasurement,                            _TXT("CSCMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::CurrentTime,                               _TXT("CurrentTime") },
    { Bluetooth::Profile::Service::Characteristic::CyclingPowerControlPoint,                  _TXT("CyclingPowerControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::CyclingPowerFeature,                       _TXT("CyclingPowerFeature") },
    { Bluetooth::Profile::Service::Characteristic::CyclingPowerMeasurement,                   _TXT("CyclingPowerMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::CyclingPowerVector,                        _TXT("CyclingPowerVector") },
    { Bluetooth::Profile::Service::Characteristic::DatabaseChangeIncrement,                   _TXT("DatabaseChangeIncrement") },
    { Bluetooth::Profile::Service::Characteristic::DateofBirth,                               _TXT("DateofBirth") },
    { Bluetooth::Profile::Service::Characteristic::DateofThresholdAssessment,                 _TXT("DateofThresholdAssessment") },
    { Bluetooth::Profile::Service::Characteristic::DateTime,                                  _TXT("DateTime") },
    { Bluetooth::Profile::Service::Characteristic::DateUTC,                                   _TXT("DateUTC") },
    { Bluetooth::Profile::Service::Characteristic::DayDateTime,                               _TXT("DayDateTime") },
    { Bluetooth::Profile::Service::Characteristic::DayofWeek,                                 _TXT("DayofWeek") },
    { Bluetooth::Profile::Service::Characteristic::DescriptorValueChanged,                    _TXT("DescriptorValueChanged") },
    { Bluetooth::Profile::Service::Characteristic::DewPoint,                                  _TXT("DewPoint") },
    { Bluetooth::Profile::Service::Characteristic::Digital,                                   _TXT("Digital") },
    { Bluetooth::Profile::Service::Characteristic::DigitalOutput,                             _TXT("DigitalOutput") },
    { Bluetooth::Profile::Service::Characteristic::DSTOffset,                                 _TXT("DSTOffset") },
    { Bluetooth::Profile::Service::Characteristic::Elevation,                                 _TXT("Elevation") },
    { Bluetooth::Profile::Service::Characteristic::EmailAddress,                              _TXT("EmailAddress") },
    { Bluetooth::Profile::Service::Characteristic::EmergencyID,                               _TXT("EmergencyID") },
    { Bluetooth::Profile::Service::Characteristic::EmergencyText,                             _TXT("EmergencyText") },
    { Bluetooth::Profile::Service::Characteristic::ExactTime100,                              _TXT("ExactTime100") },
    { Bluetooth::Profile::Service::Characteristic::ExactTime256,                              _TXT("ExactTime256") },
    { Bluetooth::Profile::Service::Characteristic::FatBurnHeartRateLowerLimit,                _TXT("FatBurnHeartRateLowerLimit") },
    { Bluetooth::Profile::Service::Characteristic::FatBurnHeartRateUpperLimit,                _TXT("FatBurnHeartRateUpperLimit") },
    { Bluetooth::Profile::Service::Characteristic::FirmwareRevisionString,                    _TXT("FirmwareRevisionString") },
    { Bluetooth::Profile::Service::Characteristic::FirstName,                                 _TXT("FirstName") },
    { Bluetooth::Profile::Service::Characteristic::FitnessMachineControlPoint,                _TXT("FitnessMachineControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::FitnessMachineFeature,                     _TXT("FitnessMachineFeature") },
    { Bluetooth::Profile::Service::Characteristic::FitnessMachineStatus,                      _TXT("FitnessMachineStatus") },
    { Bluetooth::Profile::Service::Characteristic::FiveZoneHeartRateLimits,                   _TXT("FiveZoneHeartRateLimits") },
    { Bluetooth::Profile::Service::Characteristic::FloorNumber,                               _TXT("FloorNumber") },
    { Bluetooth::Profile::Service::Characteristic::CentralAddressResolution,                  _TXT("CentralAddressResolution") },
    { Bluetooth::Profile::Service::Characteristic::DeviceName,                                _TXT("DeviceName") },
    { Bluetooth::Profile::Service::Characteristic::PeripheralPreferredConnectionParameters,   _TXT("PeripheralPreferredConnectionParameters") },
    { Bluetooth::Profile::Service::Characteristic::PeripheralPrivacyFlag,                     _TXT("PeripheralPrivacyFlag") },
    { Bluetooth::Profile::Service::Characteristic::ReconnectionAddress,                       _TXT("ReconnectionAddress") },
    { Bluetooth::Profile::Service::Characteristic::ServiceChanged,                            _TXT("ServiceChanged") },
    { Bluetooth::Profile::Service::Characteristic::Gender,                                    _TXT("Gender") },
    { Bluetooth::Profile::Service::Characteristic::GlucoseFeature,                            _TXT("GlucoseFeature") },
    { Bluetooth::Profile::Service::Characteristic::GlucoseMeasurement,                        _TXT("GlucoseMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::GlucoseMeasurementContext,                 _TXT("GlucoseMeasurementContext") },
    { Bluetooth::Profile::Service::Characteristic::GustFactor,                                _TXT("GustFactor") },
    { Bluetooth::Profile::Service::Characteristic::HardwareRevisionString,                    _TXT("HardwareRevisionString") },
    { Bluetooth::Profile::Service::Characteristic::HeartRateControlPoint,                     _TXT("HeartRateControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::HeartRateMax,                              _TXT("HeartRateMax") },
    { Bluetooth::Profile::Service::Characteristic::HeartRateMeasurement,                      _TXT("HeartRateMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::HeatIndex,                                 _TXT("HeatIndex") },
    { Bluetooth::Profile::Service::Characteristic::Height,                                    _TXT("Height") },
    { Bluetooth::Profile::Service::Characteristic::HIDControlPoint,                           _TXT("HIDControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::HIDInformation,                            _TXT("HIDInformation") },
    { Bluetooth::Profile::Service::Characteristic::HipCircumference,                          _TXT("HipCircumference") },
    { Bluetooth::Profile::Service::Characteristic::HTTPControlPoint,                          _TXT("HTTPControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::HTTPEntityBody,                            _TXT("HTTPEntityBody") },
    { Bluetooth::Profile::Service::Characteristic::HTTPHeaders,                               _TXT("HTTPHeaders") },
    { Bluetooth::Profile::Service::Characteristic::HTTPStatusCode,                            _TXT("HTTPStatusCode") },
    { Bluetooth::Profile::Service::Characteristic::HTTPSSecurity,                             _TXT("HTTPSSecurity") },
    { Bluetooth::Profile::Service::Characteristic::Humidity,                                  _TXT("Humidity") },
    { Bluetooth::Profile::Service::Characteristic::IDDAnnunciationStatus,                     _TXT("IDDAnnunciationStatus") },
    { Bluetooth::Profile::Service::Characteristic::IDDCommandControlPoint,                    _TXT("IDDCommandControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::IDDCommandData,                            _TXT("IDDCommandData") },
    { Bluetooth::Profile::Service::Characteristic::IDDFeatures,                               _TXT("IDDFeatures") },
    { Bluetooth::Profile::Service::Characteristic::IDDHistoryData,                            _TXT("IDDHistoryData") },
    { Bluetooth::Profile::Service::Characteristic::IDDRecordAccessControlPoint,               _TXT("IDDRecordAccessControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::IDDStatus,                                 _TXT("IDDStatus") },
    { Bluetooth::Profile::Service::Characteristic::IDDStatusChanged,                          _TXT("IDDStatusChanged") },
    { Bluetooth::Profile::Service::Characteristic::IDDStatusReaderControlPoint,               _TXT("IDDStatusReaderControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::IndoorBikeData,                            _TXT("IndoorBikeData") },
    { Bluetooth::Profile::Service::Characteristic::IndoorPositioningConfiguration,            _TXT("IndoorPositioningConfiguration") },
    { Bluetooth::Profile::Service::Characteristic::IntermediateCuffPressure,                  _TXT("IntermediateCuffPressure") },
    { Bluetooth::Profile::Service::Characteristic::IntermediateTemperature,                   _TXT("IntermediateTemperature") },
    { Bluetooth::Profile::Service::Characteristic::Irradiance,                                _TXT("Irradiance") },
    { Bluetooth::Profile::Service::Characteristic::Language,                                  _TXT("Language") },
    { Bluetooth::Profile::Service::Characteristic::LastName,                                  _TXT("LastName") },
    { Bluetooth::Profile::Service::Characteristic::Latitude,                                  _TXT("Latitude") },
    { Bluetooth::Profile::Service::Characteristic::LNControlPoint,                            _TXT("LNControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::LNFeature,                                 _TXT("LNFeature") },
    { Bluetooth::Profile::Service::Characteristic::LocalEastCoordinate,                       _TXT("LocalEastCoordinate") },
    { Bluetooth::Profile::Service::Characteristic::LocalNorthCoordinate,                      _TXT("LocalNorthCoordinate") },
    { Bluetooth::Profile::Service::Characteristic::LocalTimeInformation,                      _TXT("LocalTimeInformation") },
    { Bluetooth::Profile::Service::Characteristic::LocationandSpeedCharacteristic,            _TXT("LocationandSpeedCharacteristic") },
    { Bluetooth::Profile::Service::Characteristic::LocationName,                              _TXT("LocationName") },
    { Bluetooth::Profile::Service::Characteristic::Longitude,                                 _TXT("Longitude") },
    { Bluetooth::Profile::Service::Characteristic::MagneticDeclination,                       _TXT("MagneticDeclination") },
    { Bluetooth::Profile::Service::Characteristic::MagneticFluxDensity_2D,                    _TXT("MagneticFluxDensity_2D") },
    { Bluetooth::Profile::Service::Characteristic::MagneticFluxDensity_3D,                    _TXT("MagneticFluxDensity_3D") },
    { Bluetooth::Profile::Service::Characteristic::ManufacturerNameString,                    _TXT("ManufacturerNameString") },
    { Bluetooth::Profile::Service::Characteristic::MaximumRecommendedHeartRate,               _TXT("MaximumRecommendedHeartRate") },
    { Bluetooth::Profile::Service::Characteristic::MeasurementInterval,                       _TXT("MeasurementInterval") },
    { Bluetooth::Profile::Service::Characteristic::ModelNumberString,                         _TXT("ModelNumberString") },
    { Bluetooth::Profile::Service::Characteristic::Navigation,                                _TXT("Navigation") },
    { Bluetooth::Profile::Service::Characteristic::NetworkAvailability,                       _TXT("NetworkAvailability") },
    { Bluetooth::Profile::Service::Characteristic::NewAlert,                                  _TXT("NewAlert") },
    { Bluetooth::Profile::Service::Characteristic::ObjectActionControlPoint,                  _TXT("ObjectActionControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::ObjectChanged,                             _TXT("ObjectChanged") },
    { Bluetooth::Profile::Service::Characteristic::ObjectFirst_Created,                       _TXT("ObjectFirst_Created") },
    { Bluetooth::Profile::Service::Characteristic::ObjectID,                                  _TXT("ObjectID") },
    { Bluetooth::Profile::Service::Characteristic::ObjectLast_Modified,                       _TXT("ObjectLast_Modified") },
    { Bluetooth::Profile::Service::Characteristic::ObjectListControlPoint,                    _TXT("ObjectListControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::ObjectListFilter,                          _TXT("ObjectListFilter") },
    { Bluetooth::Profile::Service::Characteristic::ObjectName,                                _TXT("ObjectName") },
    { Bluetooth::Profile::Service::Characteristic::ObjectProperties,                          _TXT("ObjectProperties") },
    { Bluetooth::Profile::Service::Characteristic::ObjectSize,                                _TXT("ObjectSize") },
    { Bluetooth::Profile::Service::Characteristic::ObjectType,                                _TXT("ObjectType") },
    { Bluetooth::Profile::Service::Characteristic::OTSFeature,                                _TXT("OTSFeature") },
    { Bluetooth::Profile::Service::Characteristic::PLXContinuousMeasurementCharacteristic,    _TXT("PLXContinuousMeasurementCharacteristic") },
    { Bluetooth::Profile::Service::Characteristic::PLXFeatures,                               _TXT("PLXFeatures") },
    { Bluetooth::Profile::Service::Characteristic::PLXSpot_CheckMeasurement,                  _TXT("PLXSpot_CheckMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::PnPID,                                     _TXT("PnPID") },
    { Bluetooth::Profile::Service::Characteristic::PollenConcentration,                       _TXT("PollenConcentration") },
    { Bluetooth::Profile::Service::Characteristic::Position2D,                                _TXT("Position2D") },
    { Bluetooth::Profile::Service::Characteristic::Position3D,                                _TXT("Position3D") },
    { Bluetooth::Profile::Service::Characteristic::PositionQuality,                           _TXT("PositionQuality") },
    { Bluetooth::Profile::Service::Characteristic::Pressure,                                  _TXT("Pressure") },
    { Bluetooth::Profile::Service::Characteristic::ProtocolMode,                              _TXT("ProtocolMode") },
    { Bluetooth::Profile::Service::Characteristic::PulseOximetryControlPoint,                 _TXT("PulseOximetryControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::Rainfall,                                  _TXT("Rainfall") },
    { Bluetooth::Profile::Service::Characteristic::RCFeature,                                 _TXT("RCFeature") },
    { Bluetooth::Profile::Service::Characteristic::RCSettings,                                _TXT("RCSettings") },
    { Bluetooth::Profile::Service::Characteristic::ReconnectionConfigurationControlPoint,     _TXT("ReconnectionConfigurationControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::RecordAccessControlPoint,                  _TXT("RecordAccessControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::RegulatoryCertificationDataList,           _TXT("RegulatoryCertificationDataList") },
    { Bluetooth::Profile::Service::Characteristic::ReferenceTimeInformation,                  _TXT("ReferenceTimeInformation") },
    { Bluetooth::Profile::Service::Characteristic::Removable,                                 _TXT("Removable") },
    { Bluetooth::Profile::Service::Characteristic::Report,                                    _TXT("Report") },
    { Bluetooth::Profile::Service::Characteristic::ReportMap,                                 _TXT("ReportMap") },
    { Bluetooth::Profile::Service::Characteristic::ResolvablePrivateAddressOnly,              _TXT("ResolvablePrivateAddressOnly") },
    { Bluetooth::Profile::Service::Characteristic::RestingHeartRate,                          _TXT("RestingHeartRate") },
    { Bluetooth::Profile::Service::Characteristic::RingerControlpoint,                        _TXT("RingerControlpoint") },
    { Bluetooth::Profile::Service::Characteristic::RingerSetting,                             _TXT("RingerSetting") },
    { Bluetooth::Profile::Service::Characteristic::RowerData,                                 _TXT("RowerData") },
    { Bluetooth::Profile::Service::Characteristic::RSCFeature,                                _TXT("RSCFeature") },
    { Bluetooth::Profile::Service::Characteristic::RSCMeasurement,                            _TXT("RSCMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::SCControlPoint,                            _TXT("SCControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::ScanIntervalWindow,                        _TXT("ScanIntervalWindow") },
    { Bluetooth::Profile::Service::Characteristic::ScanRefresh,                               _TXT("ScanRefresh") },
    { Bluetooth::Profile::Service::Characteristic::ScientificTemperatureCelsius,              _TXT("ScientificTemperatureCelsius") },
    { Bluetooth::Profile::Service::Characteristic::SecondaryTimeZone,                         _TXT("SecondaryTimeZone") },
    { Bluetooth::Profile::Service::Characteristic::SensorLocation,                            _TXT("SensorLocation") },
    { Bluetooth::Profile::Service::Characteristic::SerialNumberString,                        _TXT("SerialNumberString") },
    { Bluetooth::Profile::Service::Characteristic::ServiceRequired,                           _TXT("ServiceRequired") },
    { Bluetooth::Profile::Service::Characteristic::SoftwareRevisionString,                    _TXT("SoftwareRevisionString") },
    { Bluetooth::Profile::Service::Characteristic::SportTypeforAerobicandAnaerobicThresholds, _TXT("SportTypeforAerobicandAnaerobicThresholds") },
    { Bluetooth::Profile::Service::Characteristic::StairClimberData,                          _TXT("StairClimberData") },
    { Bluetooth::Profile::Service::Characteristic::StepClimberData,                           _TXT("StepClimberData") },
    { Bluetooth::Profile::Service::Characteristic::String,                                    _TXT("String") },
    { Bluetooth::Profile::Service::Characteristic::SupportedHeartRateRange,                   _TXT("SupportedHeartRateRange") },
    { Bluetooth::Profile::Service::Characteristic::SupportedInclinationRange,                 _TXT("SupportedInclinationRange") },
    { Bluetooth::Profile::Service::Characteristic::SupportedNewAlertCategory,                 _TXT("SupportedNewAlertCategory") },
    { Bluetooth::Profile::Service::Characteristic::SupportedPowerRange,                       _TXT("SupportedPowerRange") },
    { Bluetooth::Profile::Service::Characteristic::SupportedResistanceLevelRange,             _TXT("SupportedResistanceLevelRange") },
    { Bluetooth::Profile::Service::Characteristic::SupportedSpeedRange,                       _TXT("SupportedSpeedRange") },
    { Bluetooth::Profile::Service::Characteristic::SupportedUnreadAlertCategory,              _TXT("SupportedUnreadAlertCategory") },
    { Bluetooth::Profile::Service::Characteristic::SystemID,                                  _TXT("SystemID") },
    { Bluetooth::Profile::Service::Characteristic::TDSControlPoint,                           _TXT("TDSControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::Temperature,                               _TXT("Temperature") },
    { Bluetooth::Profile::Service::Characteristic::TemperatureCelsius,                        _TXT("TemperatureCelsius") },
    { Bluetooth::Profile::Service::Characteristic::TemperatureFahrenheit,                     _TXT("TemperatureFahrenheit") },
    { Bluetooth::Profile::Service::Characteristic::TemperatureMeasurement,                    _TXT("TemperatureMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::TemperatureType,                           _TXT("TemperatureType") },
    { Bluetooth::Profile::Service::Characteristic::ThreeZoneHeartRateLimits,                  _TXT("ThreeZoneHeartRateLimits") },
    { Bluetooth::Profile::Service::Characteristic::TimeAccuracy,                              _TXT("TimeAccuracy") },
    { Bluetooth::Profile::Service::Characteristic::TimeBroadcast,                             _TXT("TimeBroadcast") },
    { Bluetooth::Profile::Service::Characteristic::TimeSource,                                _TXT("TimeSource") },
    { Bluetooth::Profile::Service::Characteristic::TimeUpdateControlPoint,                    _TXT("TimeUpdateControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::TimeUpdateState,                           _TXT("TimeUpdateState") },
    { Bluetooth::Profile::Service::Characteristic::TimewithDST,                               _TXT("TimewithDST") },
    { Bluetooth::Profile::Service::Characteristic::TimeZone,                                  _TXT("TimeZone") },
    { Bluetooth::Profile::Service::Characteristic::TrainingStatus,                            _TXT("TrainingStatus") },
    { Bluetooth::Profile::Service::Characteristic::TreadmillData,                             _TXT("TreadmillData") },
    { Bluetooth::Profile::Service::Characteristic::TrueWindDirection,                         _TXT("TrueWindDirection") },
    { Bluetooth::Profile::Service::Characteristic::TrueWindSpeed,                             _TXT("TrueWindSpeed") },
    { Bluetooth::Profile::Service::Characteristic::TwoZoneHeartRateLimit,                     _TXT("TwoZoneHeartRateLimit") },
    { Bluetooth::Profile::Service::Characteristic::TxPowerLevel,                              _TXT("TxPowerLevel") },
    { Bluetooth::Profile::Service::Characteristic::Uncertainty,                               _TXT("Uncertainty") },
    { Bluetooth::Profile::Service::Characteristic::UnreadAlertStatus,                         _TXT("UnreadAlertStatus") },
    { Bluetooth::Profile::Service::Characteristic::URI,                                       _TXT("URI") },
    { Bluetooth::Profile::Service::Characteristic::UserControlPoint,                          _TXT("UserControlPoint") },
    { Bluetooth::Profile::Service::Characteristic::UserIndex,                                 _TXT("UserIndex") },
    { Bluetooth::Profile::Service::Characteristic::UVIndex,                                   _TXT("UVIndex") },
    { Bluetooth::Profile::Service::Characteristic::VO2Max,                                    _TXT("VO2Max") },
    { Bluetooth::Profile::Service::Characteristic::WaistCircumference,                        _TXT("WaistCircumference") },
    { Bluetooth::Profile::Service::Characteristic::Weight,                                    _TXT("Weight") },
    { Bluetooth::Profile::Service::Characteristic::WeightMeasurement,                         _TXT("WeightMeasurement") },
    { Bluetooth::Profile::Service::Characteristic::WeightScaleFeature,                        _TXT("WeightScaleFeature") },
    { Bluetooth::Profile::Service::Characteristic::WindChill,                                 _TXT("WindChill") },
ENUM_CONVERSION_END(Bluetooth::Profile::Service::Characteristic::type)

ENUM_CONVERSION_BEGIN(Bluetooth::Profile::Service::type)

    { Bluetooth::Profile::Service::GenericAccess,                  _TXT("Generic Access")                },
    { Bluetooth::Profile::Service::AlertNotificationService,       _TXT("Alert Notification Service")    },
    { Bluetooth::Profile::Service::AutomationIO,                   _TXT("Automation IO")                 },
    { Bluetooth::Profile::Service::BatteryService,                 _TXT("Battery Service")               },
    { Bluetooth::Profile::Service::BinarySensor,                   _TXT("Binary Sensor")                 },
    { Bluetooth::Profile::Service::BloodPressure,                  _TXT("Blood Pressure")                },
    { Bluetooth::Profile::Service::BodyComposition,                _TXT("Body Composition")              },
    { Bluetooth::Profile::Service::BondManagementService,          _TXT("Bond Management Service")       },
    { Bluetooth::Profile::Service::ContinuousGlucoseMonitoring,    _TXT("Continuous Glucose Monitoring") },
    { Bluetooth::Profile::Service::CurrentTimeService,             _TXT("Current Time Service")          },
    { Bluetooth::Profile::Service::CyclingPower,                   _TXT("Cycling Power")                 },
    { Bluetooth::Profile::Service::CyclingSpeedAndCadence,         _TXT("Cycling Speed and Cadence")     },
    { Bluetooth::Profile::Service::DeviceInformation,              _TXT("Device Information")            },
    { Bluetooth::Profile::Service::EmergencyConfiguration,         _TXT("Emergency Configuration")       },
    { Bluetooth::Profile::Service::EnvironmentalSensing,           _TXT("Environmental Sensing")         },
    { Bluetooth::Profile::Service::FitnessMachine,                 _TXT("Fitness Machine")               },
    { Bluetooth::Profile::Service::GenericAttribute,               _TXT("Generic Attribute")             },
    { Bluetooth::Profile::Service::Glucose,                        _TXT("Glucose")                       },
    { Bluetooth::Profile::Service::HealthThermometer,              _TXT("Health Thermometer")            },
    { Bluetooth::Profile::Service::HeartRate,                      _TXT("Heart Rate")                    },
    { Bluetooth::Profile::Service::HTTPProxy,                      _TXT("HTTP Proxy")                    },
    { Bluetooth::Profile::Service::HumanInterfaceDevice,           _TXT("Human Interface Device")        },
    { Bluetooth::Profile::Service::ImmediateAlert,                 _TXT("Immediate Alert")               },
    { Bluetooth::Profile::Service::IndoorPositioning,              _TXT("Indoor Positioning")            },
    { Bluetooth::Profile::Service::InsulinDelivery,                _TXT("Insulin Delivery")              },
    { Bluetooth::Profile::Service::InternetProtocolSupport,        _TXT("Internet Protocol Support")     },
    { Bluetooth::Profile::Service::LinkLoss,                       _TXT("Link Loss")                     },
    { Bluetooth::Profile::Service::LocationAndNavigation,          _TXT("Location and Navigation")       },
    { Bluetooth::Profile::Service::MeshProvisioningService,        _TXT("Mesh Provisioning Service")     },
    { Bluetooth::Profile::Service::MeshProxyService,               _TXT("Mesh Proxy Service")            },
    { Bluetooth::Profile::Service::NextDSTChangeService,           _TXT("Next DST Change Service")       },
    { Bluetooth::Profile::Service::ObjectTransferService,          _TXT("ObjectTransferService")         },
    { Bluetooth::Profile::Service::PhoneAlertStatusService,        _TXT("Phone Alert Status Service")    },
    { Bluetooth::Profile::Service::PulseOximeterService,           _TXT("Pulse Oximeter Service")        },
    { Bluetooth::Profile::Service::ReconnectionConfiguration,      _TXT("Reconnection Configuration")    },
    { Bluetooth::Profile::Service::ReferenceTimeUpdateService,     _TXT("Reference Time Update Service") },
    { Bluetooth::Profile::Service::RunningSpeedAndCadence,         _TXT("Running Speed and Cadence")     },
    { Bluetooth::Profile::Service::ScanParameters,                 _TXT("Scan Parameters")               },
    { Bluetooth::Profile::Service::TransportDiscovery,             _TXT("Transport Discovery")           },
    { Bluetooth::Profile::Service::TxPower,                        _TXT("Tx Power")                      },
    { Bluetooth::Profile::Service::UserData,                       _TXT("User Data")                     },
    { Bluetooth::Profile::Service::WeightScale,                    _TXT("Weight Scale")                  },

ENUM_CONVERSION_END(Bluetooth::Profile::Service::type)

} // namespace WPEFramework

