include(config)

map()
    key(libprovision)
    map()
        kv(tag master)
        kv(url "git@github.com:Metrological/libprovision.git")
    end()
    key(WPEFrameworkPlugins)
    map()
        kv(tag master)
        kv(url "git@github.com:WebPlatformForEmbedded/WPEFrameworkPlugins.git")
    end()
    key(WPEPluginProvisioning)
    map()
        kv(tag master)
        kv(url "git@github.com:WebPlatformForEmbedded/WPEPluginProvisioning.git")
    end()
end()
ans(repositories)
