name: Build Thunder on Linux (R4_4)

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["development/actions-r4_4"] # change to R4_4
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'ReleaseNotes/**'
  pull_request:
    branches: ["R4_4"]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'ReleaseNotes/**'

jobs:
  Thunder:
    uses: ./.github/workflows/Linux build template.yml

#  ThunderInterfaces:
#    needs: Thunder
#    uses: rdkcentral/ThunderInterfaces/.github/workflows/Linux build template.yml@R4_4
