name: "CLA"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  contents: read
  pull-requests: write
  actions: write
  statuses: write

jobs:
  CLA-Lite:
    name: "Signature"
    uses: rdkcentral/cmf-actions/.github/workflows/cla.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT }}
