name: Documentation Required Checks

on:
  workflow_call:
  
jobs:
  Thunder:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release, MinSizeRel]

    name: Build type - ${{matrix.build_type}}
    steps:
      - run: 'echo "Changes only to the documentation, so no build required" '
